
dicriptions = { "Transfer" : [ "EMAIL TFR   ","E TFR   ","TFR-FR","ssv","e tfr","tfr-to","PAYMENT" ] }
dicriptions["University"] = [ "CANADA           GSL","OSAP","UNIV WTRLOO" ]
dicriptions["Bank Fee"] = [ "OVERLIMIT FEE","ANNUAL FEE","BANK FEES","TFR Fee","OVERDRAFT INTEREST","PODP FEE","INTEREST" ]
dicriptions["Paypal"] = [ "paypal" ]
dicriptions["Cash"] = [ "CASH WITHDRA","TD ATM","deposit","COINAMATIC" ]
dicriptions["Insurance"] = [ "ECO MUTUAL       PAY","ECONOMICAL","Insurance" ]
dicriptions["Taxes"] = [ "RIT","CANADA           PRO","CANADA           GST" ]
dicriptions["Services"] = [ "SMARTSTYLE SALON","DRIVETEST","TAX SER" ]
dicriptions["Salary"] = [ "APPZERO","ERICSSON         PAY" ]
dicriptions["Gas"] = [ "HUSKY","ROD'S TOWING & REPAIRS","goco","PETRO","E-2-F","MALLORYTOWN SOU","ESSO","SHELL","FUELCO","ULTRAMAR" ]
dicriptions["Shopping"] = [ "7-ELEVEN","7 ELEVEN","CONV. STORES","CONVENIENCE","FARAH FOODS","VALUMA","WIRELESSWAVE","STAPLES","DOLLARAMA","BAY","BENTLEY","Amazon","REXALL","FUTURE" ]
dicriptions["Groceries"] = [ "RCSS","LOBLAWS","COSTCO WHOLESAL","ZEHRS","SOBEYS","WAL-MART","SHOPPER","FRESHCO","METRO" ]
dicriptions["Hardware"] = [ "HOME DEPOT","TSC STORES","HOME HARDWARE","KW VAC SOLUTIONS","RONA","HM HWR" ]
dicriptions["Phone"] = [ "ROGERS","WIND" ]
dicriptions["Eating Out"] = [ "HMSHOST","HK TRA","LAWENDY FAMILY FOODS","CHURCHILL ARMS","BISTRO","TACO BELL","SMOKES POUTINERIE","TREAT","IRISH SHEBEEN","POPEYE'S","PIZZA","PIZZERIA","SUBWAY","ZAUQ","DAIRY QUEEN","PITA","ROYAL JASMINE","ESM","PHO DAU BO","BAKERY","FASTFOOD","DAY  NIGHT FIREWOOD","BUBBLE TEA","EAST SIDE MARIOS","PIZZA HUT","BIG FAT GREEK B","BAMIYAN KABOB","INDIAN","COFFEE","kfc","BURGER","BUFFET","HARVEY","MANCHU WOK","SUSHI","HORTONS","A & W","LANCASTER","GRILL","SHAWARMA","BASKIN","MCDONALD","CORA","MR SUB","PAPA SAMS" ]
dicriptions["Car"] = [ "HOUGHTON RUST CONTROL","INSTANT OIL","MTO RUS","LUBE","TIRE","MEINEKE","RBC LOAN PYMT" ]
dicriptions["Gifts"] = [ "SHERIDAN NURSERIES","JEWELLERY" ]
dicriptions["Parking"] = [ "OTTAWA INTERNATIONAL","PARKING","PARKI","AEROPORT" ]
dicriptions["Computers"] =[ "COMPUTERS" ]
dicriptions["Rent"] = [ "IMH POOL",]
dicriptions["Utilities"] = [ "VELCOM" ]
dicriptions["Entertainment"] = [ "CONSERVATION","GALAXY CINEMAS","DIFFERENT STROKES" ]
dicriptions["Hotel"] = [ "INN","HOTEL","MOTEL","DAYS INN" ]

